baseApp/urls.py
from django.urls import path
from . import views

app_name = 'baseApp' 
urlpatterns = [
    path('',views.HomePg,name=''),
    path('page/',views.taskList,name='page'),
    path('login/',views.LoginPg,name='log'),
    path('register/',views.RegisterPg,name='register'),
    path('index/',views.IndexPg,name='index'),
    path('profile/',views.ProfilePg,name='profile'),
    path('courses/',views.CoursesPg,name='courses'),
    path('notes/',views.NotesPg,name='notes'),
    path('analytics/',views.AnalyticsPg,name='analytics'),
    path('certifications/',views.CertificationsPg,name='certifications'),
    path('findCourses/',views.FindCoursesPg,name='findCourses'),
    path('viewCourses/',views.ViewCoursesPg,name='viewCourses')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('baseApp.urls'))
   
    
]

baseApp/models.py
from pyexpat import model
from django.db import models

# Create your models here.
class podatoci(models.Model):
    poId = models.IntegerField()
    country = models.TextField()
    Age = models.IntegerField()
    firstName = models.TextField()
    lastName = models.TextField()
    email = models.TextField()
    userCourses = models.TextField(default='')
    
class coursevi(models.Model):
    title = models.TextField()
    duration = models.TextField()
    description = models.TextField()

class UserCourses(models.Model):
    user = models.TextField()
    courses= models.TextField()

baseApp/views.py
import email
from itertools import count
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from .models import podatoci,coursevi,UserCourses


def taskList(request):
    return HttpResponse("hello my friend")
def FindCoursesPg(request):
    allCourses = coursevi.objects.all()
   
    zapisani = UserCourses.objects.get(user=request.session['mail'])
    krajnaNiza=[]
    for somet in allCourses:
        if somet.title in zapisani.courses:
            pass
        else:
            krajnaNiza.append(somet.title)
       
    if request.method=="POST":
        select = request.POST.get('testoj',False)
        korisnik = request.session['mail']
        najaven = UserCourses.objects.get(user=korisnik)
        if select in najaven.courses:
           pass
        else:
            najaven.courses = najaven.courses + select + ','
            
            najaven.save()
           
        return render(request,'baseApp/FindCourses.html',{'potr':krajnaNiza})

    return render(request,'baseApp/FindCourses.html',{'potr':krajnaNiza})
def ViewCoursesPg(request):
    broj1 = request.session['mail']
    broj2 = request.session['first']
    return render(request,'baseApp/ViewCourses.html',{'broj1':broj1,
    'broj2':broj2})
def HomePg(request):
   
   return render(request, 'baseApp/home.html')
def IndexPg(request):
    if request.method =="POST":
        title = request.POST.get('title',False)
        duration = request.POST.get('duration',False)
        desc = request.POST.get('description',False)
        courses = coursevi()
        courses.title = title
        courses.duration = duration
        courses.description = desc
        courses.save()
    return render(request,'baseApp/index.html')
def NotesPg(request):
    broj1 = request.session['mail']
    broj2 = request.session['first']
    return render(request,'baseApp/notes.html',{'broj1':broj1,
    'broj2':broj2})    
def CertificationsPg(request):
    broj1 = request.session['mail']
    broj2 = request.session['first']
    return render(request,'baseApp/certifications.html',{'broj1':broj1,
    'broj2':broj2})
def AnalyticsPg(request):
    broj1 = request.session['mail']
    broj2 = request.session['first']
    return render(request,'baseApp/analytics.html',{'broj1':broj1,
    'broj2':broj2}
    )    
def ProfilePg(request):
    broj1 = request.session['mail']
    broj2 = request.session['first']
    broj3 = request.session['last']
    broj4 = request.session['country']
    broj5 = request.session['age']

   
    return render(request,'baseApp/profile.html',{'broj1':broj1,
    'broj2':broj2,
    'broj3':broj3,
    'broj4':broj4,
    'broj5':broj5
    
    
    })
def CoursesPg(request):
    broj1 = request.session['mail']
    broj2 = request.session['first']
    korisnik = request.session['mail']
    najaven = UserCourses.objects.get(user=korisnik)
    
    niza = najaven.courses.split(',')
    niza.remove('')
    return render(request,'baseApp/courses.html',{'broj1':broj1,
    'broj2':broj2,
    'najaven':niza
    })      


def LoginPg(request):
    if request.method == "POST":
        Lemail = request.POST.get('logMail',False)
        Lpass = request.POST.get('logPass',False)

        user = authenticate(username=Lemail,password=Lpass)
        
        if user is not None:
            login(request,user)
            fname = user.first_name
            pod = podatoci.objects.get(email=Lemail) 
            request.session['mail'] = pod.email
            request.session['first'] = pod.firstName
            request.session['last'] = pod.lastName
            request.session['country'] = pod.country
            request.session['age'] = pod.Age
            

            return redirect('/profile')
        else:
            greska = 'invalid credentials'
            return render(request,'baseApp/login.html',{'greska':greska})



    return render(request, 'baseApp/login.html')

def RegisterPg(request):
   if request.method == "POST":
        fname = request.POST.get('fname',False)
        lname = request.POST.get('lname',False)
        email = request.POST.get('email',False)
        pass1 = request.POST.get('pass1',False)
        country = request.POST.get('country',False)
        age = request.POST.get('Age',False)
        
        myuser = User.objects.create_user(email,fname,pass1)
        myuser.first_name = fname
        myuser.last_name = lname
       
        myuser.save()

        podatok = podatoci()
        podatok.poId = 1
        podatok.firstName = fname
        podatok.lastName = lname
        podatok.country = country
        podatok.email = email
        podatok.Age = age
        

        podatok.save()

        UserCasovi = UserCourses()
        UserCasovi.user = email
        UserCasovi.courses=''
        UserCasovi.save()

        
        return redirect('/login')
   else:
        return render(request,'baseApp/register.html')

            
   
  
   

   




 

   
  
  

baseApp/templates/baseApp/Certifications.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script>
  var myCollapse = document.getElementById('accordion')
var bsCollapse = new bootstrap.Collapse(myCollapse, {
  toggle: true
});
</script>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div style="margin-left:5rem;"  class="container-fluid">
    <a class="navbar-brand" href="#">CyberSecurity</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse justify-content-between navbar-collapse" id="navbarNavAltMarkup">
      <div style="font-weight: bold;" class="navbar-nav">
        <a class="nav-link active" href="{% url 'baseApp:profile' %}">Profile</a>
        <a class="nav-link active" href="{% url 'baseApp:findCourses' %}">Find Courses</a>
        <a class="nav-link active" href="{% url 'baseApp:' %}">Main Page</a>
        <div class="dropdown show">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"  data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Learning Paths
          </a>
        
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="#">Begginer</a>
            <a class="dropdown-item" href="#">Intermediate</a>
            <a class="dropdown-item" href="#">Advanced</a>
          </div>
        </div>
      </div>
      <div class="navbar-bar">
        <a href="{% url 'baseApp:' %}"><Button href="../home.html"  class="btn btn-primary">Log Out</Button></a>
      </div>
    </div>
  </div>
</nav>
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-4 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"><span class="font-weight-bold">{{broj2}}</span><span class="text-black-50">{{broj1}}</span><span> </span></div>
        </div>
        <div class="col-md-8 border-right">
            <div class="p-3 py-5">
                <div class=" align-items-center mb-4">
                    <div style="background-color: white;" class="container-fluid">
                      <a style="margin-left:18rem;" href="{% url 'baseApp:' %}">Back to Home Page Link</a>
                        <nav style="background-color:white !important;" class="navbar navbar-expand-lg navbar-light bg-light">
                            <a class="navbar-brand" href="#"></a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                              <span class="navbar-toggler-icon"></span>
                            </button>
                            
                          
                            <div style="background-color: white;" class=" justify-content-between navbar-collapse" id="navbarSupportedContent">
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:profile' %}">Profile</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:courses' %}">My Courses</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:notes' %}">Notes</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:analytics' %}">Analytics</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:certifications' %}">Certifications</span></a>
                                </li>
                              </ul>
                              
                                
                              

                             
                            </div>
                          </nav>
                    </div>
                   
                   
                </div>
                <h2 style="margin-bottom: 10px; padding-left:10px;">Certifications</h2>
                <h1>No Certifications Yet</h1>
               
   </div>
</div>

baseApp/templates/baseApp/ViewCourses.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div style="margin-left:5rem;"  class="container-fluid">
      <a class="navbar-brand" href="#">CyberSecurity</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse justify-content-between navbar-collapse" id="navbarNavAltMarkup">
        <div style="font-weight: bold;" class="navbar-nav">
          <a class="nav-link active" href="{% url 'baseApp:profile' %}">Profile</a>
          <a class="nav-link active" href="{% url 'baseApp:findCourses' %}">Find Courses</a>
          <a class="nav-link active" href="{% url 'baseApp:' %}">Main Page</a>
          <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"  data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Learning Paths
            </a>
          
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="#">Begginer</a>
              <a class="dropdown-item" href="#">Intermediate</a>
              <a class="dropdown-item" href="#">Advanced</a>
            </div>
          </div>
        </div>
        <div class="navbar-bar">
            <Button  class="btn btn-primary">Log Out</Button>
        </div>
      </div>
    </div>
  </nav>



<div class="justify-content-end  row mt-3">
    <div class="col-2">
       <a href="{% url 'baseApp:courses' %}"> <button class="btn btn-primary">Go back to My Courses</button></a>
    </div>
</div>

<div  class="row">
    
    
    <div class="col-2">
        <h2>Notifications</h2>
        <p>Some news about the specific course</p>
        
    </div>
    <div  class="col-10">
        <div style="border-left: 5px solid red;"  class="container-fluid">
          <h1>Course Name: The Course Name</h1>
          <h2>Materials needed for the Specific course</h2>
            <ul class="list-group list-group-flush">
                <h2></h2>
                <li class="list-group-item">Material 1</li>
                <li class="list-group-item">Material 2</li>
                <li class="list-group-item">Material 3</li>
                <li class="list-group-item">Material 4</li>
                <li class="list-group-item">Material 5</li>
                

            </ul>

        </div>

   </div>
       

    </div>  
</div>
<div class="row m-3">
    <h1>Course Progress</h1>
    <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
      </div>
</div>

baseApp/templates/baseApp/analytics.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script>
  var myCollapse = document.getElementById('accordion')
var bsCollapse = new bootstrap.Collapse(myCollapse, {
  toggle: true
});
</script>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div style="margin-left:5rem;"  class="container-fluid">
    <a class="navbar-brand" href="#">CyberSecurity</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse justify-content-between navbar-collapse" id="navbarNavAltMarkup">
      <div style="font-weight: bold;" class="navbar-nav">
        <a class="nav-link active" href="{% url 'baseApp:profile' %}">Profile</a>
        <a class="nav-link active" href="{% url 'baseApp:findCourses' %}">Find Courses</a>
        <a class="nav-link active" href="{% url 'baseApp:' %}">Main Page</a>
        <div class="dropdown show">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"  data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Learning Paths
          </a>
        
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="#">Begginer</a>
            <a class="dropdown-item" href="#">Intermediate</a>
            <a class="dropdown-item" href="#">Advanced</a>
          </div>
        </div>
      </div>
      <div class="navbar-bar">
        <a href="{% url 'baseApp:' %}"><Button href="../home.html"  class="btn btn-primary">Log Out</Button></a>
      </div>
    </div>
  </div>
</nav>
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-4 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"><span class="font-weight-bold">{{broj2}}</span><span class="text-black-50">{{broj1}}</span><span> </span></div>
        </div>
        <div class="col-md-8 border-right">
            <div class="p-3 py-5">
                <div class=" align-items-center mb-4">
                    <div style="background-color: white;" class="container-fluid">
                      <a style="margin-left:18rem;" href="{% url 'baseApp:' %}">Back to Home Page Link</a>
                        <nav style="background-color:white !important;" class="navbar navbar-expand-lg navbar-light bg-light">
                            <a class="navbar-brand" href="#"></a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                              <span class="navbar-toggler-icon"></span>
                            </button>
                            
                          
                            <div style="background-color: white;" class=" justify-content-between navbar-collapse" id="navbarSupportedContent">
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:profile' %}">Profile</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:courses' %}">My Courses</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:notes' %}">Notes</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:analytics' %}">Analytics</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:certifications' %}">Certifications</span></a>
                                </li>
                              </ul>
                              
                                
                              

                             
                            </div>
                          </nav>
                    </div>
                   
                   
                </div>
                <h2 style="margin-bottom: 10px; padding-left:10px;">Analytics Chart</h2>
                    <div class="col-8">
                      <ul class="list-group">
                        <li class="list-group-item">Attendance Procent:</li>
                        <li class="list-group-item">Average Grade:</li>
                        <li class="list-group-item">Courses Finished:</li>
                        <li class="list-group-item">Performance level:</li>
                      
                      </ul>
                    </div>
                
                </div>


               
   </div>
</div>

baseApp/templates/baseApp/courses.html
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div style="margin-left:5rem;"  class="container-fluid">
    <a class="navbar-brand" href="#">CyberSecurity</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse justify-content-between navbar-collapse" id="navbarNavAltMarkup">
      <div style="font-weight: bold;" class="navbar-nav">
        <a class="nav-link active" href="{% url 'baseApp:profile' %}">Profile</a>
        <a class="nav-link active" href="{% url 'baseApp:findCourses' %}">Find Courses</a>
        <a class="nav-link active" href="{% url 'baseApp:' %}">Main Page</a>
        <div class="dropdown show">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"  data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Learning Paths
          </a>
        
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="#">Begginer</a>
            <a class="dropdown-item" href="#">Intermediate</a>
            <a class="dropdown-item" href="#">Advanced</a>
          </div>
        </div>
      </div>
      <div class="navbar-bar">
        <a href="{% url 'baseApp:' %}"><Button href="../home.html"  class="btn btn-primary">Log Out</Button></a>
      </div>
    </div>
  </div>
</nav>
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-4 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"><span class="font-weight-bold">{{broj2}}</span><span class="text-black-50">{{broj1}}</span><span> </span></div>
        </div>
        <div class="col-md-8 border-right">
            <div class="p-3 py-5">
                <div class=" align-items-center mb-4">
                    <div style="background-color: white;" class="container-fluid">
                      <a style="margin-left:18rem;" href="{% url 'baseApp:' %}">Back to Home Page Link</a>
                        <nav style="background-color:white !important;" class="navbar navbar-expand-lg navbar-light bg-light">
                            <a class="navbar-brand" href="#"></a>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                              <span class="navbar-toggler-icon"></span>
                            </button>
                            
                          
                            <div style="background-color: white;" class=" justify-content-between navbar-collapse" id="navbarSupportedContent">
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:profile' %}">Profile</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:courses' %}">My Courses</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:notes' %}">Notes</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:analytics' %}">Analytics</span></a>
                                </li>
                              </ul>
                              <ul class="justify-content-between navbar-nav mr-auto">
                                <li class="nav-item active">
                                  <a class="nav-link" href="{% url 'baseApp:certifications' %}">Certifications</span></a>
                                </li>
                              </ul>
                              
                             
                            </div>
                          </nav>
                    </div>
                   
                   
                </div>
                <h2 style="margin-bottom: 10px; padding-left:10px;">ENROLED Courses</h2>
                <div class="row m-1">
                  {% for item in najaven %}
                   <input name="testoj" id="testoj"  type="hidden" value="{{item.title}}">
                  
                   <div class="card m-2" style="width: 14rem;">
                     <img style="max-height:14rem;" class="card-img-top" src="{% static 'baseApp/img/back.jpg' %}" alt="Card image cap">
                     <div class="card-body">
                       <h5 class="card-title">{{item.title}}</h5>
                       <p class="card-text">Duis bibendum et nisl quis malesuada. Aenean lacus sem, interdum in pellentesque id, vehicula nec nulla.</p>
                    
                           <button type="submit" name="kopce" id="kopce" class="btn btn-primary">Go somewhere</button>
                    
                      
                     </div>
                   </div>
                   {% if forloop.counter|divisibleby:4 %}</div><div class="row m-1">{% endif %}
                   {% endfor %}
               </div>
               
            
                         
                </div>
            </div>
        </div>
       
    </div>
</div>
</div>
</div>

baseApp/templates/baseApp/index.html
<p1>
{% for podatok in potr %}
  {{podatok.title}}
 
{% endfor %}
Helooo
</p1>
<form method="POST">
  {% csrf_token %}
  <input type="text" name="title" id="title">
<input type="text" name="duration" id="duration">
<input type="text" name="description" id="description">
<button type="submit">Submit the Course</button>
</form>